#switches 
#input 1
set_property PACKAGE_PIN V17 [get_ports {byte_1[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_1[0]}]
set_property PACKAGE_PIN V16 [get_ports {byte_1[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_1[1]}]
set_property PACKAGE_PIN W16 [get_ports {byte_1[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_1[2]}]
set_property PACKAGE_PIN W17 [get_ports {byte_1[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_1[3]}]
#input 2
set_property PACKAGE_PIN W15 [get_ports {byte_2[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_2[0]}]
set_property PACKAGE_PIN V15 [get_ports {byte_2[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_2[1]}]
set_property PACKAGE_PIN W14 [get_ports {byte_2[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_2[2]}]
set_property PACKAGE_PIN W13 [get_ports {byte_2[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {byte_2[3]}]
# pick ALU FUNC
set_property PACKAGE_PIN V2 [get_ports {switches[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]
set_property PACKAGE_PIN T3 [get_ports {switches[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]

#carry_in 
set_property PACKAGE_PIN R2 [get_ports {carry_in}]
set_property IOSTANDARD LVCMOS33 [get_ports {carry_in}]
#seven_segment_display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

# anodes
set_property PACKAGE_PIN U2 [get_ports {anodes[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
set_property PACKAGE_PIN U4 [get_ports {anodes[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property PACKAGE_PIN V4 [get_ports {anodes[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property PACKAGE_PIN W4 [get_ports {anodes[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]
#LED

set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]

set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property PACKAGE_PIN W18 [get_ports {led_2[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_2[0]}]
set_property PACKAGE_PIN U15 [get_ports {led_2[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_2[1]}]
set_property PACKAGE_PIN U14 [get_ports {led_2[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_2[2]}]
set_property PACKAGE_PIN V14 [get_ports {led_2[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_2[3]}]
